/// Ana ekran, ayarlar, hesap, günlük ödül, ses servisi metinleri (Türkçe → İngilizce).
const Map<String, String> enAna = {
  '🎉 Oyun daveti': '🎉 Game invite',
  '{kim} seni "{oda}" odasına çağırıyor.': '{kim} is inviting you to the room "{oda}".',
  'Şimdi değil': 'Not now',
  'Katıl': 'Join',
  'Giriş gerekli': 'Sign-in required',
  '{ozellik} için giriş yapmalısın. Şimdiye kadarki ilerlemen hesabına bağlanır.': 'You need to sign in to use {ozellik}. Your progress so far will be linked to your account.',
  'Online oyun': 'Online play',
  'Giriş yap': 'Sign in',
  'Botlara karşı': 'Versus bots',
  'Kaç bota karşı?': 'How many bots?',
  '{n} oyuncu · sen + {b} bot': '{n} players · you + {b} bot(s)',
  'Bot zorluğu': 'Bot difficulty',
  'Kolay': 'Easy',
  'Normal': 'Normal',
  'Zor': 'Hard',
  'Kolay bot fırsatların bir kısmını kaçırır, Reddet kartını nadiren kullanır.': 'Easy bots miss some opportunities and rarely use the Just Say No card.',
  'Normal bot mantıklı oynar.': 'Normal bots play sensibly.',
  'Zor bot her fırsatı kullanır, elini erken zenginleştirir.': 'Hard bots take every opportunity and build up their hand early.',
  'Oyunu başlat': 'Start game',
  'Müzik': 'Music',
  'Oyuncu sesleri': 'Player voices',
  'Seviye {n}': 'Level {n}',
  'Günlük ödül (giriş gerekli)': 'Daily reward (sign-in required)',
  'Günlük ödülünü al': 'Claim your daily reward',
  'Günlük ödül': 'Daily reward',
  '🧪 Animasyonu dene (ödül verilmez)': '🧪 Try the animation (no reward)',
  'Kaldığın yerden devam et': 'Continue where you left off',
  'Yeni oyun (botlara karşı)': 'New game (versus bots)',
  'Botlara karşı oyna': 'Play versus bots',
  'Online oyna': 'Play online',
  'Dükkân': 'Shop',
  'Arkadaşlar': 'Friends',
  'Başarımlar': 'Achievements',
  'Nasıl oynanır': 'How to play',
  'Türkiye şehirleri tapu kart oyunu': 'The Turkish cities property card game',
  'Sunucuya ulaşılamadı.': 'Could not reach the server.',
  '🎉 Büyük kutu açıldı: +{n} altın!': '🎉 Big box opened: +{n} gold!',
  '🎁 +{n} altın!': '🎁 +{n} gold!',
  'Bugünkü ödül zaten alınmış.': 'Today\'s reward has already been claimed.',
  'Giriş yap, her gün ödül kazan. Seriyi bozma: 7. günün büyük kutusu seni bekliyor!': 'Sign in and earn a reward every day. Don\'t break the streak: the big box is waiting on day 7!',
  '{gun}. gün ödülün hazır! Her gün gir, seri bozulmasın.': 'Your day {gun} reward is ready! Come back every day to keep the streak.',
  'Bugünkü ödülünü aldın. Yarın: {n} altın': 'You claimed today\'s reward. Tomorrow: {n} gold',
  ' (BÜYÜK KUTU)': ' (BIG BOX)',
  '{gun}. gün': 'Day {gun}',
  '💰 {n} altın': '💰 {n} gold',
  '7. GÜN · BÜYÜK KUTU': 'DAY 7 · BIG BOX',
  'Sonraki gün seri başa döner': 'The streak resets after that',
  'Ödülü al': 'Claim reward',
  'Tamam': 'OK',
  '🎁 Günlük Ödül': '🎁 Daily Reward',
  'Giriş yap, ödülü al': 'Sign in, claim reward',
  'Sunucu hatası {n}': 'Server error {n}',
  'Sunucuya ulaşılamadı ({hata})': 'Could not reach the server ({hata})',
  'Sunucuya ulaşılamadı': 'Could not reach the server',
  'Google girişi henüz ayarlanmadı.': 'Google sign-in is not set up yet.',
  'Google girişi iptal edildi.': 'Google sign-in was cancelled.',
  'Facebook girişi henüz ayarlanmadı.': 'Facebook sign-in is not set up yet.',
  'Facebook girişi iptal edildi.': 'Facebook sign-in was cancelled.',
  'Apple girişi iptal edildi.': 'Apple sign-in was cancelled.',
  'Giriş yapılamadı: {e}': 'Could not sign in: {e}',
  'Günlük görevler': 'Daily quests',
  'Günlük görevler için giriş yapmalısın.': 'You need to sign in for daily quests.',
  'Her gün yeni görevler gelir. Tamamla, ödülü al: ekstra XP ve altın!': 'New quests every day. Complete them and claim extra XP and gold!',
  'Bugünkü bot oyunu kotası': 'Today\'s bot-game quota',
  'Al': 'Claim',
  '3 oyun oyna': 'Play 3 games',
  '2 oyun kazan': 'Win 2 games',
  '1 online oyun oyna': 'Play 1 online game',
  '1 online oyun kazan': 'Win 1 online game',
  'Botlara karşı 3 oyun kazan': 'Win 3 games against bots',
  'Zor botlara karşı 1 oyun kazan': 'Win 1 game against hard bots',
  '4 veya 5 kişilik bir oyun kazan': 'Win a game with 4 or 5 players',
  'Herkes aynı miktarı yatırır, gerçek oyuncuların toplamı kazanana gider. Bot kazanırsa herkese iade edilir.': 'Everyone puts in the same amount and the real players\' total goes to the winner. If a bot wins, everyone is refunded.',
  'Altın yetmez': 'Not enough gold',
  'Oyundan çıkılsın mı?': 'Leave the game?',
  'Devam et': 'Keep playing',
  'Çık': 'Leave',
  '🏆 Havuzu kazandın!': '🏆 You won the pot!',
  '💸 Bahsini kaybettin': '💸 You lost your bet',
  'Reddet ve yardımcı kartlar': 'Reject and helper cards',
  'Reddet: sana oynanan bir hamleyi iptal eder (hamle harcamaz); karşı taraf da Reddet ile karşılık verebilir. Ev Partisi: herkesten 2M alırsın. 2 Kart Çek: desteden 2 kart çekersin. Ev Partisi ve 2 Kart Çek birer hamle harcar.': 'Reject: cancels an action played against you (uses no move); the other player can answer with a Reject too. Housewarming: collect 2M from everyone. Draw 2: draw 2 cards from the deck. Housewarming and Draw 2 use 1 move each.',
  'Botlu oyunlardan günde en çok 10.000 altın kazanılır; sınır dolunca XP devam eder, altın gelmez.': 'You can earn at most 10,000 gold per day from bot games; once the limit is reached XP continues but no gold is given.',
  'Her gün yeni görevler gelir; tamamlayınca ekstra XP ve altın alırsın. Botlu oyunlardan günde en çok 10.000 altın kazanılır; sınır dolunca XP devam eder, altın gelmez.': 'New quests arrive every day; complete them for extra XP and gold. You can earn at most 10,000 gold per day from bot games; once the limit is reached XP continues but no gold is given.',
  'Günlük sınıra ulaştın: botlu oyunlar bugün altın vermez. Online oyunlarda sınır yok.': 'You\'ve hit the daily limit: bot games give no gold today. Online games have no limit.',
  'Botlu oyunlardan günde en çok {n} altın kazanılır ({k} kullanıldı). Online oyunlarda sınır yok.': 'You can earn at most {n} gold per day from bot games ({k} used). Online games have no limit.',
  'Oda tutarı seçmelisin.': 'You must choose a room amount.',
  'Online oyun için en az 2 gerçek oyuncu gerekir.': 'An online game needs at least 2 real players.',
  'Online oyun için herkesin giriş yapmış olması gerekir.': 'Everyone must be signed in for an online game.',
  '🏆 Ödülü kazandın!': '🏆 You won the prize!',
  '↩️ Bot kazandı: altının iade edildi': '↩️ A bot won: your gold was refunded',
  '🚪 Oyundan düştüğün için altının kayboldu': '🚪 You dropped out, so your gold is lost',
  '💸 Altınını kaybettin': '💸 You lost your gold',
  'Günlük bot altın sınırına ulaştın; bugün botlu oyunlar altın vermez. Online oyunlarda sınır yok.': 'You\'ve reached the daily bot gold limit; bot games give no gold today. Online games have no limit.',
  'Oyun iptal oldu, altının iade edildi.': 'The game was cancelled; your gold was refunded.',
  'Altınlı bir oyundasın. Çıkarsan {n} altınını kaybedersin.': 'You\'re in a gold game. If you leave, you lose your {n} gold.',
  '🎉 Seviye {l}!': '🎉 Level {l}!',
  'Seviye {l}': 'Level {l}',
  'Oda tutarı (altın)': 'Room amount (gold)',
  'Herkes bu kadar altınla girer, gerçek oyuncuların toplamı kazanana gider. Bot kazanırsa herkese iade edilir.': 'Everyone enters with this much gold and the real players\' total goes to the winner. If a bot wins, everyone is refunded.',
  'Online oda kurmak için en az 50 altın gerekir. Şu an: {n} altın': 'You need at least 50 gold to create an online room. You have: {n} gold',
  'Altının: {n}': 'Your gold: {n}',
  'Odaya giriş: {n} altın ödendi': 'Room entry: {n} gold paid',
  'Oyun başlayamadı, altının iade edildi.': 'The game could not start; your gold was refunded.',
  '{n} altınlık': '{n}-gold',
  '💰 {n} altınlık oda': '💰 {n}-gold room',
  'Ödül: {n} altın (gerçek oyuncu sayısı × oda tutarı)': 'Prize: {n} gold (real players × room amount)',
  'Online oyun için en az 2 gerçek oyuncu gerekir': 'An online game needs at least 2 real players',
  'Altınına uygun açık oda yok. Kendi odanı kurabilirsin.': 'No open room fits your gold. You can create your own.',
  'Online oda ve altın': 'Online rooms and gold',
  'Online oyunlar altınlı odalarda oynanır: odayı kuran tutarı seçer (50, 100, 250…), herkes o kadar altınla girer ve gerçek oyuncuların toplamı kazanana gider. Bot kazanırsa herkesin altını iade edilir; oyundan düşersen altının kaybolur. XP sadece online oyunlardan kazanılır. Botlu oyunlar altın biriktirmek içindir.': 'Online games are played in gold rooms: the room creator picks an amount (50, 100, 250…), everyone enters with that much gold and the real players\' total goes to the winner. If a bot wins, everyone\'s gold is refunded; if you drop out, your gold is lost. XP is earned only in online games. Bot games are for saving up gold.',
  'Her gün yeni görevler gelir; tamamlayınca ekstra XP ve altın alırsın. Botlu oyunlardan günde en çok 10.000 altın kazanılır; sınır dolunca o gün altın gelmez.': 'New quests arrive every day; complete them for extra XP and gold. You can earn at most 10,000 gold per day from bot games; once the limit is reached no more gold that day.',
};
