/// Şikayet, engelleme, hesap silme ve gizlilik metinleri (Türkçe → İngilizce).
const Map<String, String> enGuvenlik = {
  'Seviye {lv} ve {altin} altınınla buraya kadar geldin. Gitmene üzülürüz, kalmaya ne dersin?': "You've come this far with Level {lv} and {altin} gold. We'd hate to see you go. How about staying?",
  'Hakaret / küfür': 'Harassment / profanity',
  'Uygunsuz isim': 'Inappropriate name',
  'Hile': 'Cheating',
  'Spam': 'Spam',
  'Diğer': 'Other',
  'Sayfa açılamadı.': 'Could not open the page.',
  'Gizlilik Politikası': 'Privacy Policy',
  'Devam ederek Gizlilik Politikasını kabul etmiş olursun.': 'By continuing, you accept the Privacy Policy.',
  '{ad} şikayet edilsin mi?': 'Report {ad}?',
  'Şikayet nedenini seç:': 'Choose a reason:',
  'Not (isteğe bağlı)': 'Note (optional)',
  'Gönder': 'Send',
  'Şikayetin alındı, teşekkürler.': 'Your report was received, thank you.',
  '{ad} engellensin mi?': 'Block {ad}?',
  'Engellenen kişinin sohbet mesajlarını, emojilerini ve konuşmalarını görmez, duymazsın. Engeli Arkadaşlar ekranından kaldırabilirsin.': 'You will not see or hear chat messages, emojis or speech from a blocked player. You can unblock them from the Friends screen.',
  'Engelle': 'Block',
  '{ad} engellendi.': '{ad} was blocked.',
  'Şikayet et': 'Report',
  'Engeli kaldır': 'Unblock',
  '{ad} için engel kaldırıldı.': '{ad} was unblocked.',
  'Hesabı sil': 'Delete account',
  'Hesabın ve ona bağlı tüm veriler kalıcı olarak silinir. Bu işlem geri alınamaz.': 'Your account and all data linked to it will be permanently deleted. This cannot be undone.',
  'Silinecekler:': 'What will be deleted:',
  'Profilin, nickname ve avatarın': 'Your profile, nickname and avatar',
  'Seviye, XP ve altınların': 'Your level, XP and gold',
  'Dükkândan aldığın eşyalar': 'Items you bought in the shop',
  'Arkadaş listen ve engellerin': 'Your friends list and blocks',
  'Oyun geçmişin ve başarımların': 'Your game history and achievements',
  'Bağlı e-posta, Google ve Facebook girişin': 'Your linked e-mail, Google and Facebook sign-in',
  'Hesap silme sayfası': 'Account deletion page',
  'Devam': 'Continue',
  'Son onay': 'Final confirmation',
  'Hesabımın ve verilerimin kalıcı olarak silineceğini anlıyorum.': 'I understand my account and data will be permanently deleted.',
  'Onaylamak için SIL yaz': 'Type SIL to confirm',
  'Parolan': 'Your password',
  'Hesabı kalıcı sil': 'Delete permanently',
  'Hesabın silindi. Misafir olarak devam edebilirsin.': 'Your account was deleted. You can continue as a guest.',
  'Arkadaşlıktan çıkar': 'Remove friend',
  'Engellenenler': 'Blocked players',
};
