/// Kart tasarımı metinleri (Türkçe → İngilizce).
const Map<String, String> enKart = {
  'TAPU SENEDİ · {s}': 'TITLE DEED · {s}',
  '{s} TAPUSU': '{s} DEED',
  'KİRA BEDELİ': 'RENT',
  'Tek tapu': 'Single deed',
  '{n} tapu': '{n} deeds',
  '{n} tapu (tam set)': '{n} deeds (full set)',
  '{n} ulaşım tapusu': '{n} transport',
  '{n} altyapı tapusu': '{n} utilities',
  'Tam set + Ev': 'Full set + House',
  '+ Ev + Rezidans': '+ House + Residence',
  'JOKER · {s}': 'WILD · {s}',
  'JOKER TAPU': 'WILD DEED',
  'JOKER KİRA': 'WILD RENT',
  'Her renk': 'Any color',
  'Her renkli set': 'Any color set',
  'Bu kartı dilediğin renkli setin yerine koy. Rengini sonradan değiştirebilirsin. Tek başına para değeri yoktur.': 'Use this card in any color set. You can change its color later. It has no cash value on its own.',
  'BİR MİLYON': 'ONE MILLION',
  'İKİ MİLYON': 'TWO MILLION',
  'ÜÇ MİLYON': 'THREE MILLION',
  'DÖRT MİLYON': 'FOUR MILLION',
  'BEŞ MİLYON': 'FIVE MILLION',
  'ON MİLYON': 'TEN MILLION',
  'AKSİYON': 'ACTION',
  'GELİŞTİRME': 'UPGRADE',
  'HERKESTEN': 'FROM EVERYONE',
  'kira al': 'collect rent',
  'istediğin renkten kira al': 'collect rent in any color',
};
