/// Oyun ekranı, diyaloglar, masa, kart metinleri (Türkçe → İngilizce).
const Map<String, String> enOyun = {
  'Kahverengi': 'Brown',
  'Açık Mavi': 'Light Blue',
  'Mor': 'Purple',
  'Turuncu': 'Orange',
  'Kırmızı': 'Red',
  'Sarı': 'Yellow',
  'Yeşil': 'Green',
  'Lacivert': 'Dark Blue',
  'Siyah': 'Black',
  'Turkuaz': 'Turquoise',
  'Kahve': 'Brown',
  'A. Mavi': 'L. Blue',
  'Haciz': 'Seizure',
  'Reddet': 'Reject',
  'Tapu Devri': 'Deed Transfer',
  'Takas Pazarlığı': 'Swap Meet',
  'İcra Takibi': 'Pay Up',
  'Ev Partisi': 'Housewarming',
  '2 Kart Çek': 'Draw 2',
  'Ev': 'House',
  'Rezidans': 'Residence',
  'Zam Geldi': 'Rent Hike',
  'Rakibin TAM bir setini (ev/rezidans dahil) çal.': 'Steal a COMPLETE set (with house/residence) from an opponent.',
  'Sana oynanan bir aksiyonu iptal et.': 'Cancel an action played against you.',
  'Rakipten tamamlanmamış setten bir tapu çal.': 'Steal a property from an opponent\'s incomplete set.',
  'Rakiple bir tapu takas et (tam setler hariç).': 'Swap a property with an opponent (complete sets excluded).',
  'Bir rakipten 5M tahsil et.': 'Collect 5M from one opponent.',
  'Her oyuncudan 2M al.': 'Collect 2M from every player.',
  '2 kart çek.': 'Draw 2 cards.',
  'Tam bir sete koy: kira +3M.': 'Add to a complete set: rent +3M.',
  'Evli tam sete koy: kira +4M.': 'Add to a set with a house: rent +4M.',
  'Bir kira kartıyla oyna: kira 2 katı.': 'Play with a rent card: double the rent.',
  'Joker Tapu': 'Wild Property',
  'Joker': 'Wild',
  'Joker Kira': 'Wild Rent',
  'Kira': 'Rent',
  'kira': 'rent',
  'Kira {a}/{b}': 'Rent {a}/{b}',
  'Ulaşım': 'Transport',
  'Altyapı': 'Utilities',
  'Sabiha Gökçen Havalimanı': 'Sabiha Gökçen Airport',
  'Esenboğa Havalimanı': 'Esenboğa Airport',
  'Eskihisar Feribot İskelesi': 'Eskihisar Ferry Pier',
  'Topçular Feribot İskelesi': 'Topçular Ferry Pier',
  'Kabataş Vapur İskelesi': 'Kabataş Ferry Pier',
  'Haydarpaşa Tren İstasyonu': 'Haydarpaşa Train Station',
  'Sirkeci Tren İstasyonu': 'Sirkeci Train Station',
  'Kadıköy Deniz Yolları': 'Kadıköy Sea Lines',
  'Doğalgaz İdaresi': 'Natural Gas Authority',
  'Telekom Altyapısı': 'Telecom Infrastructure',
  'Elektrik İdaresi': 'Electricity Authority',
  'Sular İdaresi': 'Water Authority',
  'Ödeme': 'Payment',
  '{a} turuna başladı — kart çekiyor.': '{a} started their turn — drawing cards.',
  '{a} {b} kart attı.': '{a} discarded {b} cards.',
  '🏆 {a} 3 tam setle kazandı!': '🏆 {a} won with 3 complete sets!',
  '{a} {b} tapusunu {c} setine koydu.': '{a} placed {b} into the {c} set.',
  '{a} jokeri {b} setine taşıdı.': '{a} moved the wild to the {b} set.',
  '{a} {b} kartını {c}M para olarak bankaya koydu.': '{a} banked {b} as {c}M cash.',
  '{a} {b} kartını bankaya koydu.': '{a} banked {b}.',
  '{a} ödeyecek hiçbir şeyi yok.': '{a} has nothing to pay with.',
  '{a} → {b}: {c} için {d}M ödedi.': '{a} → {b}: paid {d}M for {c}.',
  '{a} Reddet oynadı — aksiyon iptal!': '{a} played Reject — action cancelled!',
  '{a} Reddet oynadı — reddi reddetti!': '{a} played Reject — rejected the rejection!',
  '{a} Reddet oynadı — {b} iptal!': '{a} played Reject — {b} cancelled!',
  '{a} Reddet ile karşılık verdi — talep yeniden geçerli!': '{a} countered with Reject — the demand is back on!',
  '{a} 2 Kart Çek oynadı: 2 kart çekti.': '{a} played Draw 2: drew 2 cards.',
  '{a} İcra Takibi: {b} 5M ödemeli.': '{a} Pay Up: {b} must pay 5M.',
  '{a} Ev Partisi: herkes 2M veriyor.': '{a} Housewarming: everyone pays 2M.',
  '{a} {b} kirası: {c}M (çift) — herkes öder.': '{a} {b} rent: {c}M (double) — everyone pays.',
  '{a} {b} kirası: {c}M — herkes öder.': '{a} {b} rent: {c}M — everyone pays.',
  '{a} Tapu Devri: {b} çalmak istiyor.': '{a} Deed Transfer: wants to steal {b}.',
  '{a} {b} tapusunu aldı.': '{a} took the {b} deed.',
  '{a} Takas Pazarlığı: {b} ↔ {c}.': '{a} Swap Meet: {b} ↔ {c}.',
  '{a} Haciz: {b} setini istiyor!': '{a} Seizure: wants the {b} set!',
  '{a} {b} setini aldı!': '{a} took the {b} set!',
  '{a} {b} setine {c} koydu.': '{a} added {c} to the {b} set.',
  'İcra Takibi ({a}M)': 'Pay Up ({a}M)',
  'Ev Partisi ({a}M)': 'Housewarming ({a}M)',
  '{a} kirası ({b}M)': '{a} rent ({b}M)',
  'Tapu Devri ({a})': 'Deed Transfer ({a})',
  'Takas Pazarlığı ({a})': 'Swap Meet ({a})',
  'Haciz ({a} seti)': 'Seizure ({a} set)',
  'Reddet ({a} {b} ödemeyi reddetti)': 'Reject ({a} refused the {b} payment)',
  'Deste bitti, atılanlar karıştırıldı.': 'Deck is empty, the discard pile was shuffled.',
  'Takas yapıldı.': 'Swap completed.',
  'Sunucu bağlantısı koptu.': 'Server connection lost.',
  'Süre doldu, tur geçti.': 'Time\'s up, turn skipped.',
  'Sıra sende!': 'It\'s your turn!',
  'Sen': 'You',
  'Rakip': 'Opponent',
  'Mesaj yaz…': 'Type a message…',
  '🏆 Kazandın!': '🏆 You won!',
  '😔 {ad} kazandı': '😔 {ad} won',
  '{ad} 3 tam set topladı: {setler}.': '{ad} collected 3 complete sets: {setler}.',
  '{ad}: {n} tam set · {m}M varlık': '{ad}: {n} complete sets · {m}M assets',
  '+{xp} XP  ·  +{altin} altın': '+{xp} XP  ·  +{altin} gold',
  '  ·  🎉 Seviye {l}!': '  ·  🎉 Level {l}!',
  '  ·  Seviye {l}': '  ·  Level {l}',
  'Toplam: {o} oyun, {k} galibiyet (%{oran})': 'Total: {o} games, {k} wins ({oran}%)',
  'Menüye dön': 'Back to menu',
  'Lobiye dön': 'Back to lobby',
  'Revanş': 'Rematch',
  '🏅 Yeni başarım: {liste}': '🏅 New achievement: {liste}',
  'Sıra sende değil.': 'It\'s not your turn.',
  'Hamle hakkın bitti.': 'You are out of moves.',
  'Bu hamle yapılamadı.': 'That move couldn\'t be made.',
  '💰 Kira iste': '💰 Charge rent',
  '▶ 2 Kart Çek': '▶ Draw 2 Cards',
  '💵 İcra Takibi: 5M al': '💵 Pay Up: take 5M',
  '🎉 Ev Partisi: herkesten 2M': '🎂 Housewarming: 2M from everyone',
  '🕵️ Tapu Devri: rakipten tapu al': '🕵️ Deed Transfer: take a deed from an opponent',
  '🔁 Takas Pazarlığı: tapu takası': '🔁 Swap Meet: trade deeds',
  '💥 Haciz: tam seti al': '💥 Seizure: take a complete set',
  '🏗️ {ad} koy (tam sete)': '🏗️ Add {ad} (to a complete set)',
  '✖2 Çift kira (kira kartıyla)': '✖2 Double rent (with a rent card)',
  'ℹ️ Sadece savunmada oynanır': 'ℹ️ Can only be played in defense',
  'Reddet kartı, rakip sana aksiyon oynayınca sorulur.': 'The Reject card is offered when an opponent plays an action on you.',
  '🏦 Bankaya koy ({n}M para olur)': '🏦 Bank it (becomes {n}M cash)',
  'şu an oynanamaz': 'can\'t be played right now',
  '🏦 {n}M · varlık {m}M': '🏦 {n}M · assets {m}M',
  'Vazgeç': 'Cancel',
  'Kimsenin ödeyecek bir şeyi yok.': 'Nobody has anything to pay with.',
  '💵 Kimden 5M?': '💵 5M from whom?',
  'Bu renkte tapun yok.': 'You have no deeds in this color.',
  '✖2 Zam Geldi?': '✖2 Rent Hike?',
  'Zam Geldi kartını da oynayıp {n}M isteyeyim mi? (2 hamle harcar)': 'Play the Rent Hike card too and charge {n}M? (uses 2 moves)',
  'Evet, çift': 'Yes, double',
  'Hayır, tek': 'No, single',
  'Evet': 'Yes',
  'Hayır': 'No',
  'Tamam': 'OK',
  'Oynanabilir kira kartın yok.': 'You have no playable rent card.',
  'Çift kira için 2 hamle gerekir.': 'Double rent needs 2 moves.',
  'Hangi kira kartıyla?': 'Which rent card?',
  'Rakiplerde alınabilir tapu yok (tam setler korunur).': 'No deeds can be taken from opponents (complete sets are protected).',
  '🕵️ Hangi tapuyu alıyorsun?': '🕵️ Which deed are you taking?',
  'Değiş tokuş için iki tarafta da tamamlanmamış setten tapu olmalı.': 'A swap needs a deed from an incomplete set on both sides.',
  '🔁 Rakipten hangisini alıyorsun?': '🔁 Which one do you take from the opponent?',
  '🔁 Karşılığında hangisini veriyorsun?': '🔁 Which one do you give in return?',
  'Rakiplerin tam seti yok.': 'Opponents have no complete sets.',
  '💥 Kimin setini alıyorsun?': '💥 Whose set are you taking?',
  'tam set: {liste}': 'complete sets: {liste}',
  '💥 Hangi tam seti?': '💥 Which complete set?',
  'Evsiz tam setin yok.': 'You have no complete set without a house.',
  'Evli (rezidanssız) tam setin yok.': 'You have no complete set with a house (and no residence).',
  '🏗️ Hangi sete?': '🏗️ Which set?',
  'Kartlar dağıtılıyor…': 'Dealing cards…',
  'Oyun bitti': 'Game over',
  '{ad} oynuyor…': '{ad} is playing…',
  'Sıra sende · {n} hamle': 'Your turn · {n} moves',
  'Emlak Deal · {n} oyuncu': 'Emlak Deal · {n} players',
  'Sohbet / emoji': 'Chat / emoji',
  'Sesi kapat': 'Mute voices',
  'Sesi aç': 'Unmute voices',
  'Tam set {n}/3': 'Complete sets {n}/3',
  'Turu bitir': 'End turn',
  'Henüz kart yok': 'No cards yet',
  '🏦 {n} kart': '🏦 {n} cards',
  'kira {n}M': 'rent {n}M',
  'Elin ({n}/7)': 'Your hand ({n}/7)',
  'Gereken: {n}M · Seçilen: {m}M': 'Required: {n}M · Selected: {m}M',
  '{n} kart seç · Seçilen: {m}': 'Pick {n} cards · Selected: {m}',
  '{ad} ({n} kart · {m}M)': '{ad} ({n} cards · {m}M)',
  '— yok —': '— none —',
  '🛑 Reddet?': '🛑 Reject?',
  'Rakip sana şunu oynadı: {a}\n\nElindeki Reddet kartıyla iptal etmek ister misin?': 'Your opponent played this on you: {a}\n\nDo you want to cancel it with your Reject card?',
  '💸 {ad}\'a {n}M öde': '💸 Pay {ad} {n}M',
  'Varlığın {n}M — tutar bunu aşıyor, hepsini seçmen gerekir.': 'Your assets are {n}M — the amount exceeds that, you must select everything.',
  '🃏 Joker hangi renk olsun?': '🃏 Which color should the wild be?',
  '🗑️ El limiti 7 — {n} kart at': '🗑️ Hand limit 7 — discard {n} cards',
  'Öde': 'Pay',
  'At': 'Discard',
  'Reddet!': 'Reject!',
  'Kabul et': 'Accept',
  'Reddet kartıyla iptal et': 'Cancel with Reject card',
  '💵 Para': '💵 Cash',
  '🏠 Tapular': '🏠 Properties',
  '{ad} masasına bak': 'View {ad}\'s table',
  'Tepeden bak': 'Top-down view',
  'BOŞ': 'EMPTY',
  'YAKILAN': 'DISCARD',
  '{ad} · Sv {n}': '{ad} · Lv {n}',
  'set {n}/3 · {m}M': 'sets {n}/3 · {m}M',
  'SAHİP OLUNAN\nTAPU SENEDİ\nSAYISI': 'DEEDS\nOWNED',
  'KİRA': 'RENT',
  'TAM SET': 'COMPLETE SET',
  'Joker Tapu\nSenedi Kartı': 'Wild Property\nDeed Card',
  'Renklerden birini seç': 'Choose one of the colors',
  'JOKER TAPU\nSENEDİ KARTI': 'WILD PROPERTY\nDEED CARD',
  'Bu kart herhangi bir renk\ngrubunda tapu olarak\nkullanılabilir.': 'This card can be used\nas a property in any\ncolor group.',
  'HAMLE KARTI': 'ACTION CARD',
  'Herhangi bir rengin kirasını herkesten al.': 'Charge any color of rent from everyone.',
  '{a} veya {b} kirasını herkesten al.': 'Charge {a} or {b} rent from everyone.',
};
