/// Lobi, arkadaşlar, profil, dükkân, başarımlar, öğretici metinleri (Türkçe → İngilizce).
const Map<String, String> enSosyal = {
  'İlk Zafer': 'First Victory',
  'İlk oyununu kazan.': 'Win your first game.',
  'Alışkanlık': 'Habit',
  '3 oyun kazan.': 'Win 3 games.',
  'Usta': 'Master',
  '10 oyun kazan.': 'Win 10 games.',
  'Masa Başı': 'At the Table',
  '10 oyun oyna.': 'Play 10 games.',
  'Kalabalık Masa': 'Crowded Table',
  '4 bota karşı kazan.': 'Win against 4 bots.',
  'Zor Lokma': 'Tough Nut',
  'Zor botlara karşı kazan.': 'Win against hard bots.',
  'Patron': 'Tycoon',
  'Bankanda 20M ile oyunu bitir.': 'Finish the game with 20M in your bank.',
  'Hacizci': 'Repo Man',
  'Haciz kartıyla tam set al.': 'Take a full set with a Seizure card.',
  'Hayır Dedim': 'I Said No',
  'Bir saldırıyı Reddet ile iptal et.': 'Cancel an attack with Reject.',
  'Sosyal Kelebek': 'Social Butterfly',
  'Online bir oyun kazan.': 'Win an online game.',
  'Seri': 'Streak',
  'Üst üste 3 oyun kazan.': 'Win 3 games in a row.',
  'Şimşek': 'Lightning',
  'Oyunu 10 turdan kısa sürede kazan.': 'Win a game in fewer than 10 turns.',
  'Sunucuya ulaşılamadı.': 'Couldn\'t reach the server.',
  'Başarımlar': 'Achievements',
  'Rozetler {a}/{b}': 'Badges {a}/{b}',
  'Liderlik': 'Leaderboard',
  'Seri: {seri} galibiyet · Toplam {oyun} oyun, {gal} galibiyet': 'Streak: {seri} wins · Total {oyun} games, {gal} wins',
  'Sv': 'Lv',
  '{xp} XP · {gal} galibiyet / {oyun} oyun': '{xp} XP · {gal} wins / {oyun} games',
  '{n} online': '{n} online',
  'Eklendi.': 'Added.',
  'Arkadaşlar & Geçmiş': 'Friends & History',
  'Arkadaşlar': 'Friends',
  'Geçmiş': 'History',
  'Takma adla ekle': 'Add by nickname',
  'Ekle': 'Add',
  'Henüz arkadaş yok. Takma adıyla ekle; çevrim içiyse odana davet edebilirsin.': 'No friends yet. Add someone by nickname; if they\'re online you can invite them to your room.',
  'Çevrim içi · odada ({oda})': 'Online · in a room ({oda})',
  'Çevrim içi': 'Online',
  'Çevrim dışı': 'Offline',
  'Davet et': 'Invite',
  'Henüz oyun yok.': 'No games yet.',
  'Galibiyet': 'Win',
  'Mağlubiyet': 'Loss',
  'online': 'online',
  'botla': 'vs bots',
  '{n} rakip': '{n} opponents',
  '+{xp} XP, +{altin} altın': '+{xp} XP, +{altin} gold',
  'Son {n} oyun: {g} galibiyet (%{oran})': 'Last {n} games: {g} wins ({oran}%)',
  'Son 10 oyun': 'Last 10 games',
  'G': 'W',
  'M': 'L',
  'Sunucu bağlantısı koptu.': 'Connection to the server was lost.',
  'Sunucuya bağlanılamadı.': 'Couldn\'t connect to the server.',
  '🔒 Özel oda': '🔒 Private room',
  'Oda şifresi': 'Room password',
  'Vazgeç': 'Cancel',
  'Katıl': 'Join',
  'Katılınabilecek açık oda yok. Kendi odanı kurabilirsin.': 'There are no open rooms to join. You can create your own.',
  'Kodla katıl': 'Join with code',
  'Oda kodu (4 harf)': 'Room code (4 letters)',
  'Oda kur': 'Create room',
  'Bot sayısı': 'Number of bots',
  'Özel oda': 'Private room',
  'Girmek için şifre gerekir': 'A password is required to enter',
  'Odayı aç': 'Open the room',
  'Şifre yanlış.': 'Wrong password.',
  'Online oyun için giriş yapmalısın.': 'You need to sign in to play online.',
  '{ad} odası': '{ad}\'s room',
  '{n} oyuncu': '{n} players',
  ' + {n} bot': ' + {n} bots',
  'süresiz': 'no limit',
  '{n} sn': '{n} s',
  ' · özel': ' · private',
  'Dolu': 'Full',
  '{ad} olarak oynuyorsun': 'Playing as {ad}',
  'Rastgele katıl': 'Join random',
  'Açık odalar': 'Open rooms',
  'Şu an açık oda yok.\nİlk odayı sen kur!': 'There are no open rooms right now.\nCreate the first one!',
  'ODA KODU': 'ROOM CODE',
  '🔒 Özel oda · şifreyi arkadaşınla paylaş': '🔒 Private room · share the password with your friend',
  'Herkese açık oda': 'Public room',
  'Arkadaş davet et': 'Invite a friend',
  'Oda sahibi': 'Room owner',
  'bekliyor': 'waiting',
  'Tur süresi': 'Turn time',
  'Yok': 'None',
  '60 sn': '60 s',
  '120 sn': '120 s',
  '180 sn': '180 s',
  '1 bot': '1 bot',
  '2 bot': '2 bots',
  '3 bot': '3 bots',
  'Oyunu başlat': 'Start game',
  'Herkesin hazır olması bekleniyor': 'Waiting for everyone to be ready',
  'Tur süresi: {x}': 'Turn time: {x}',
  'yok': 'none',
  'Hazırım ✓ (vazgeç)': 'I\'m ready ✓ (undo)',
  'Hazırım': 'I\'m ready',
  'Oda sahibinin başlatması bekleniyor…': 'Waiting for the room owner to start…',
  'Online oyun': 'Online game',
  'Oda': 'Room',
  'Tekrar dene': 'Try again',
  'Dükkâna ulaşılamadı.': 'Couldn\'t reach the shop.',
  'Satın alındı!': 'Purchased!',
  'Seçildi.': 'Selected.',
  'Dükkân': 'Shop',
  'Altın; oyun sonu ödülleri ve günlük bonusla kazanılır.': 'Gold is earned from end-of-game rewards and the daily bonus.',
  'Satın almak için giriş yapmalısın. Gezinebilirsin.': 'You need to sign in to buy. You can still browse.',
  'Giriş yap': 'Sign in',
  'Kart arkası': 'Card back',
  'Klasik (kırmızı)': 'Classic (red)',
  'Masa çuhası': 'Table felt',
  'Yeşil çuha': 'Green felt',
  'Avatarlar': 'Avatars',
  'Seçili': 'Selected',
  'Sende var': 'Owned',
  '{n} altın': '{n} gold',
  'Seç': 'Select',
  'Al · {n}': 'Buy · {n}',
  'Kaydedildi.': 'Saved.',
  'E-posta hesaba bağlandı; başka cihazdan bu bilgilerle giriş yapabilirsin.': 'Email linked to your account; you can sign in with these details on another device.',
  'Devam': 'Continue',
  'Çıkış yapılsın mı?': 'Sign out?',
  'Bu cihazda yeni bir misafir hesapla başlarsın. Bağlı hesabına tekrar girince ilerlemen geri gelir.': 'You\'ll start with a new guest account on this device. Your progress comes back when you sign in to your linked account again.',
  'Çıkış yapıldı.': 'Signed out.',
  '{ad} ile giriş': 'Sign in with {ad}',
  'Bu {ad} hesabı daha önce kullanıldıysa o hesabın ilerlemesi açılır ve bu cihazdaki misafir ilerlemen (Seviye {lv}) bırakılır. İlk kez kullanılıyorsa misafir ilerlemen hesaba bağlanır. Devam edilsin mi?': 'If this {ad} account has been used before, its progress will be opened and your guest progress on this device (Level {lv}) will be left behind. If it is new, your guest progress will be linked to the account. Continue?',
  '{ad} hesabına geçildi; önceki ilerlemen geri geldi.': 'Switched to your {ad} account; your previous progress is back.',
  '{ad} hesaba bağlandı.': '{ad} linked to your account.',
  'Hesap değişecek': 'The account will change',
  'Bu cihazdaki misafir hesabın (Seviye {lv}) bağlı olmadığı için bırakılır. Devam edilsin mi?': 'Your guest account on this device (Level {lv}) isn\'t linked, so it will be left behind. Continue?',
  'Giriş yapıldı.': 'Signed in.',
  'Avatarını seç': 'Choose your avatar',
  'En yüksek seviye': 'Max level',
  'Seviye {lv}  ·  💰 {altin} altın': 'Level {lv}  ·  💰 {altin} gold',
  'Profil': 'Profile',
  'Sunucuya ulaşılamadı; bağlanınca giriş yapabilirsin.': 'Couldn\'t reach the server; you can sign in once connected.',
  'Oyun: {o}  ·  Galibiyet: {g}': 'Games: {o}  ·  Wins: {g}',
  'Misafir olarak oynuyorsun': 'You\'re playing as a guest',
  'Giriş yapınca: online oyun, arkadaşlar, günlük ödül, dükkân, kendi nickname, avatar ve sesin açılır. Şu ana kadarki ilerlemen hesabına bağlanır; uygulamayı silersen misafir ilerlemesi gider.': 'Signing in unlocks online play, friends, the daily reward, the shop, your own nickname, avatar and voice. Your progress so far is linked to your account; if you delete the app, guest progress is lost.',
  'Sunucuya ulaşılamadı; profil çevrimdışı. Bağlanınca kaydedilir.': 'Couldn\'t reach the server; profile is offline. It will be saved once connected.',
  'Nickname (masada görünür)': 'Nickname (shown at the table)',
  'Oyundaki sesin': 'Your in-game voice',
  'Kadın': 'Female',
  'Erkek': 'Male',
  'kararlı': 'determined',
  'neşeli': 'cheerful',
  'genç': 'young',
  'ağırbaşlı': 'dignified',
  'hafif': 'light',
  'Profili kaydet': 'Save profile',
  'İstatistikler': 'Statistics',
  'Oyun: {o}  ·  Galibiyet: {g}  ·  Online: {og}/{oo}': 'Games: {o}  ·  Wins: {g}  ·  Online: {og}/{oo}',
  'Toplam XP: {xp}': 'Total XP: {xp}',
  '✅ Hesabın güvende': '✅ Your account is safe',
  'Telefon değişse bile aynı yöntemle girince ilerlemen geri gelir.': 'Even if you change phones, signing in the same way brings your progress back.',
  '🔵 Google bağlı': '🔵 Google linked',
  '🔷 Facebook bağlı': '🔷 Facebook linked',
  '🍎 Apple bağlı': '🍎 Apple linked',
  'Çıkış yap / başka hesaba geç': 'Sign out / switch account',
  '{ad} bağlı': '{ad} linked',
  '{ad} ile bağlan': 'Connect with {ad}',
  'E-posta': 'Email',
  'Şifre (en az 6)': 'Password (min. 6)',
  'E-postayı bu hesaba bağla': 'Link email to this account',
  'Mevcut hesaba giriş yap': 'Sign in to an existing account',
  'Atla': 'Skip',
  'Başla': 'Start',
  'İleri': 'Next',
  'Amaç': 'Goal',
  'Farklı renkte 3 TAM tapu seti toplayan kazanır. Set boyları kartın üstünde yazar (2, 3 ya da 4 tapu).': 'The first player to collect 3 COMPLETE property sets of different colors wins. Set sizes are printed on the card (2, 3 or 4 properties).',
  'Tur': 'Turn',
  'Her tur 2 kart çek (elin boşsa 5). En fazla 3 hamle yaparsın; 3. hamlede tur kendiliğinden biter. Tapu ya da para kartına bir kez dokun: tapu sete, para bankaya gider. Tur sonunda elinde en fazla 7 kart kalabilir.': 'Draw 2 cards each turn (5 if your hand is empty). You can make at most 3 moves; the turn ends automatically after the 3rd. Tap a property or money card once: properties go to a set, money goes to the bank. At the end of your turn you can keep at most 7 cards in hand.',
  'Para ve ödeme': 'Money and payment',
  'Hamle ve kira kartları bankaya konursa para olur; geri alınamaz. Borç banka ve tapulardan ödenir, elden ödenmez. Yetmezse her şeyini verirsin. Soluk görünen kartın işlevi şu an oynanamaz, yine de bankaya konabilir.': 'Action and rent cards placed in the bank become money and can\'t be taken back. Debts are paid from the bank and properties, never from your hand. If you can\'t cover it, you give everything you have. A faded card can\'t be played right now, but you can still put it in the bank.',
  'Kira': 'Rent',
  'Kira kartı: o renkte tapun varsa HERKESTEN kira alırsın (Joker kira her renk için geçerlidir). Zam Geldi ile iki katı (2 hamle harcar).': 'Rent card: if you own properties of that color, you collect rent from EVERYONE (a Wild Rent card works for any color). Rent Hike doubles it (uses 2 moves).',
  'Saldırı kartları': 'Attack cards',
  'Tapu Devri: tam olmayan setten bir tapu al. Takas Pazarlığı: tapu takas et (tam setler hariç). Haciz: rakibin TAM setini ev/rezidansıyla birlikte al. İcra Takibi: seçtiğin birinden 5M. Her biri 1 hamle harcar.': 'Deed Transfer: take a property from an incomplete set. Swap Meet: swap properties (complete sets excluded). Seizure: take a rival\'s COMPLETE set along with its house/residence. Pay Up: collect 5M from a player of your choice. Each uses 1 move.',
  'Ev ve rezidans': 'Houses and residences',
  'Ev (+3M) ve Rezidans (+4M) sadece TAM setlere konur. Her sete bir Ev konur; Rezidans için önce Ev gerekir. Ulaşım ve Altyapı setlerine konmaz.': 'House (+3M) and Residence (+4M) can only be placed on COMPLETE sets. Each set takes one House, and a Residence needs a House first. They can\'t be placed on Station or Utility sets.',
  'Joker': 'Wild',
  'Joker tapular istediğin renkte sayılır. Kendi turunda masadaki jokere dokunup rengini değiştirebilirsin.': 'Wild properties count as any color you choose. On your own turn, tap a wild on the table to change its color.',
  'Masa': 'Table',
  'Masayı parmağınla döndür, iki parmakla yakınlaştır. Sağ alttaki rozetlerle oyuncuya odaklan, tepeden bak, sıfırla.': 'Rotate the table with your finger and pinch with two fingers to zoom. Use the badges at the bottom right to focus on a player, look from above, or reset.',
};
