/// Kart adları, renkler, aksiyonlar, dükkân eşyaları ve sunucu mesajları (Türkçe → İngilizce).
/// Anahtar, motorda/sunucuda geçen Türkçe metnin birebiridir. İlçe/şehir adları bilerek yok (Türkçe kalır).
const Map<String, String> enVeri = {
  // --- renk setleri (PColor.ad / kisaAd)
  'Kahverengi': 'Brown',
  'Kahve': 'Brown',
  'Açık Mavi': 'Light Blue',
  'A. Mavi': 'L. Blue',
  'Mor': 'Purple',
  'Turuncu': 'Orange',
  'Kırmızı': 'Red',
  'Sarı': 'Yellow',
  'Yeşil': 'Green',
  'Lacivert': 'Navy',
  'Siyah': 'Black',
  'Turkuaz': 'Turquoise',
  'Ulaşım': 'Transport',
  'Altyapı': 'Utilities',
  // --- ulaşım / altyapı tapuları
  'Sabiha Gökçen Havalimanı': 'Sabiha Gökçen Airport',
  'Esenboğa Havalimanı': 'Esenboğa Airport',
  'Eskihisar Feribot İskelesi': 'Eskihisar Ferry Pier',
  'Topçular Feribot İskelesi': 'Topçular Ferry Pier',
  'Kabataş Vapur İskelesi': 'Kabataş Ferry Pier',
  'Haydarpaşa Tren İstasyonu': 'Haydarpaşa Train Station',
  'Sirkeci Tren İstasyonu': 'Sirkeci Train Station',
  'Kadıköy Deniz Yolları': 'Kadıköy Sea Lines',
  'Doğalgaz İdaresi': 'Natural Gas Authority',
  'Telekom Altyapısı': 'Telecom Network',
  'Elektrik İdaresi': 'Electricity Authority',
  'Sular İdaresi': 'Water Authority',
  // --- kartlar
  'Joker Tapu': 'Wild Property',
  'Joker': 'Wild',
  'Joker Kira': 'Wild Rent',
  'Kira': 'Rent',
  'Haciz': 'Seizure',
  'Reddet': 'Reject',
  'Tapu Devri': 'Deed Transfer',
  'Takas Pazarlığı': 'Swap Meet',
  'İcra Takibi': 'Pay Up',
  'Ev Partisi': 'Housewarming',
  '2 Kart Çek': 'Draw 2',
  'Ev': 'House',
  'Rezidans': 'Residence',
  'Zam Geldi': 'Rent Hike',
  'kira': 'rent',
  'Rakibin TAM bir setini (ev/rezidans dahil) çal.': "Steal an opponent's COMPLETE set (including house/residence).",
  'Sana oynanan bir aksiyonu iptal et.': 'Cancel an action played against you.',
  'Rakipten tamamlanmamış setten bir tapu çal.': 'Steal a title from an incomplete set.',
  'Rakiple bir tapu takas et (tam setler hariç).': 'Swap a title with an opponent (complete sets excluded).',
  'Bir rakipten 5M tahsil et.': 'Collect 5M from an opponent.',
  'Her oyuncudan 2M al.': 'Take 2M from every player.',
  '2 kart çek.': 'Draw 2 cards.',
  'Tam bir sete koy: kira +3M.': 'Add to a complete set: rent +3M.',
  'Evli tam sete koy: kira +4M.': 'Add to a complete set with a house: rent +4M.',
  'Bir kira kartıyla oyna: kira 2 katı.': 'Play with a rent card: rent doubled.',
  // --- ses tanımları
  'kararlı': 'steady',
  'neşeli': 'cheerful',
  'genç': 'young',
  'ağırbaşlı': 'dignified',
  'hafif': 'light',
  // --- dükkân
  'Altın Kart Arkası': 'Gold Card Back',
  'Gece Mavisi Kart Arkası': 'Midnight Blue Card Back',
  'Mermer Kart Arkası': 'Marble Card Back',
  'Bordo Çuha': 'Burgundy Felt',
  'Lacivert Çuha': 'Navy Felt',
  'Siyah Çuha (VIP)': 'Black Felt (VIP)',
  'Özel Avatarlar (8 adet)': 'Special Avatars (8)',
  'Böyle bir eşya yok.': 'No such item.',
  'Zaten sende.': 'You already own it.',
  'Bu kart arkası sende yok.': "You don't own this card back.",
  'Bu masa sende yok.': "You don't own this table.",
  // --- hesap / giriş / profil
  'Online oyun için giriş yapmalısın.': 'You need to sign in to play online.',
  'Misafir hesapta profil değiştirilemez. Giriş yap.': 'A guest profile cannot be changed. Please sign in.',
  'Günlük ödül için giriş yapmalısın.': 'You need to sign in for the daily reward.',
  'Satın almak için giriş yapmalısın.': 'You need to sign in to buy.',
  'Arkadaşlar için giriş yapmalısın.': 'You need to sign in to use friends.',
  'Nickname 3-16 karakter; harf, rakam, alt çizgi.': 'Nickname must be 3-16 characters: letters, digits, underscore.',
  'Bu nickname alınmış.': 'This nickname is taken.',
  'Geçersiz ses.': 'Invalid voice.',
  'Geçersiz avatar.': 'Invalid avatar.',
  'Geçersiz e-posta.': 'Invalid e-mail address.',
  'Şifre en az 6 karakter.': 'Password must be at least 6 characters.',
  'Bu e-posta başka hesapta.': 'This e-mail belongs to another account.',
  'E-posta ya da şifre yanlış.': 'Wrong e-mail or password.',
  'Çok fazla yanlış deneme. 10 dakika sonra tekrar dene.': 'Too many wrong attempts. Try again in 10 minutes.',
  'Token yok.': 'Missing token.',
  'Bilinmeyen sağlayıcı.': 'Unknown provider.',
  'Google girişi doğrulanamadı.': 'Google sign-in could not be verified.',
  'Facebook girişi doğrulanamadı.': 'Facebook sign-in could not be verified.',
  'Google girişi sunucuda henüz ayarlanmadı.': 'Google sign-in is not set up on the server yet.',
  'Facebook girişi sunucuda henüz ayarlanmadı.': 'Facebook sign-in is not set up on the server yet.',
  'cihaz anahtarı yok': 'missing device key',
  'oturum yok': 'no session',
  'yok': 'not found',
  // --- arkadaşlar
  'Böyle bir oyuncu yok.': 'No such player.',
  'Kendini ekleyemezsin.': "You can't add yourself.",
  'Davet gönderilemedi.': 'Invitation could not be sent.',
  // --- oda / oyun
  'Sıra sende değil.': "It's not your turn.",
  'Önceki hamle sürüyor, bekle.': 'The previous move is still in progress, please wait.',
  'Bu oda özel, şifre gerekli.': 'This room is private; a password is required.',
  'Şifre yanlış.': 'Wrong password.',
  'Oyun başlamış.': 'The game has already started.',
  'Oda dolu (en çok 5 oyuncu).': 'The room is full (5 players max).',
  'Deste bitti, atılanlar karıştırıldı.': 'The deck ran out; the discard pile was reshuffled.',
  'Takas yapıldı.': 'Swap done.',
  'Bu isim uygun değil.': "This name isn't allowed.",
  'Bu oyuncuya istek gönderemezsin.': "You can't send a request to this player.",
  'Önce engeli kaldırmalısın.': 'You need to unblock this player first.',
  'Kendini şikayet edemezsin.': "You can't report yourself.",
  'Kendini engelleyemezsin.': "You can't block yourself.",
  'Geçersiz şikayet nedeni.': 'Invalid report reason.',
  'Hesap bulunamadı.': 'Account not found.',
  'Onay gerekli.': 'Confirmation required.',
  'Çok fazla istek.': 'Too many requests.',
  'İstek çok büyük.': 'Request too large.',
  'Geçersiz istek.': 'Invalid request.',
};
